### ISSUE TITLE
why the btc balance getting less？

### ISSUE THREAD

**Issue by cnspot** [thejshen/BittrexArbitrageBot#3]
> D:\project\git\BittrexArbitrageBot>node arbitrageBot.js
-----Initializing structures-----
**Starting BTC Balance: 1**
Checking---STRAT---
BTC-STRAT ask: 0.001077
ETH-STRAT bid: 0.01539887
BTC-ETH bid: 0.07040465
Profit: 0.41241157043974397%
Starting with 1 BTC
Arbitrage on STRAT
Bought 926.183844011142 STRAT coins
Bought 14.226529148502786 ETH
***BTC after arbitrage: 0.9991097709015989***

**Comment by cnspot** [comment]
profit is 0.41241157043974397%， but result of btc balance become less( start:1  after arbitrage: 0.9991097709015989),   is something wrong?

**Comment by zjasonshen** [comment]
Might be a bug in the code.
